config/routes.rb
Rails.application.routes.draw do
  api_version(:default => true, :module => "V1",  :path => {:value => "v1"}, :header => {:name => "Accept", :value => "application/vnd.primedia.com; version=1"}, :parameter => {:name => "version", :value => "1"}) do
    resources :apps
    resources :hooks
    resources :repos

  end

end

app/controllers/v1/apps_controller.rb
class V1::AppsController < V1::BaseController
  before_action :set_app, only: [:show, :edit, :update, :destroy]

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
  end

  # GET /apps/new
  def new
    @app = App.new
  end

  # GET /apps/1/edit
  def edit
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(app_params)

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render :show, status: :created, location: @app }
      else
        format.html { render :new }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apps/1
  # PATCH/PUT /apps/1.json
  def update
    respond_to do |format|
      if @app.update(app_params)
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { render :show, status: :ok, location: @app }
      else
        format.html { render :edit }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app.destroy
    respond_to do |format|
      format.html { redirect_to apps_url, notice: 'App was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app
      @app = App.includes(:repo).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_params
      params.require(:app).permit(:name, :description, :host_group, :metadata)
    end
end

app/controllers/v1/base_controller.rb
class V1::BaseController < ApplicationController
end

app/controllers/v1/hooks_controller.rb
class V1::HooksController < V1::BaseController
  before_action :set_hook, only: [:show, :edit, :update, :destroy]

  # GET /hooks
  # GET /hooks.json
  def index
    @hooks = Hook.all
  end

  # GET /hooks/1
  # GET /hooks/1.json
  def show
  end

  # GET /hooks/new
  def new
    @hook = Hook.new
  end

  # GET /hooks/1/edit
  def edit
  end

  # POST /hooks
  # POST /hooks.json
  def create
    @hook = Hook.new(hook_params)

    respond_to do |format|
      if @hook.save
        format.html { redirect_to @hook, notice: 'Hook was successfully created.' }
        format.json { render :show, status: :created, location: @hook }
      else
        format.html { render :new }
        format.json { render json: @hook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hooks/1
  # PATCH/PUT /hooks/1.json
  def update
    respond_to do |format|
      if @hook.update(hook_params)
        format.html { redirect_to @hook, notice: 'Hook was successfully updated.' }
        format.json { render :show, status: :ok, location: @hook }
      else
        format.html { render :edit }
        format.json { render json: @hook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hooks/1
  # DELETE /hooks/1.json
  def destroy
    @hook.destroy
    respond_to do |format|
      format.html { redirect_to hooks_url, notice: 'Hook was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hook
      @hook = Hook.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hook_params
      params.require(:hook).permit(:name, :payload)
    end
end

app/controllers/v1/repos_controller.rb
class V1::ReposController < V1::BaseController
  before_action :set_repo, only: [:show, :edit, :update, :destroy]

  # GET /repos
  # GET /repos.json
  def index
    @repos = Repo.all
  end

  # GET /repos/1
  # GET /repos/1.json
  def show
  end

  # GET /repos/new
  def new
    @repo = Repo.new
  end

  # GET /repos/1/edit
  def edit
  end

  # POST /repos
  # POST /repos.json
  def create
    @repo = Repo.new(repo_params)

    respond_to do |format|
      if @repo.save
        format.html { redirect_to @repo, notice: 'Repo was successfully created.' }
        format.json { render :show, status: :created, location: @repo }
      else
        format.html { render :new }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repos/1
  # PATCH/PUT /repos/1.json
  def update
    respond_to do |format|
      if @repo.update(repo_params)
        format.html { redirect_to @repo, notice: 'Repo was successfully updated.' }
        format.json { render :show, status: :ok, location: @repo }
      else
        format.html { render :edit }
        format.json { render json: @repo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repos/1
  # DELETE /repos/1.json
  def destroy
    @repo.destroy
    respond_to do |format|
      format.html { redirect_to repos_url, notice: 'Repo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repo
      @repo = Repo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repo_params
      params.require(:repo).permit(:name, :organization, :full_name, :public)
    end
end

app/views/v1/apps/_form.html.slim
.col-lg-6
  .well.bs-component

    = form_for @app do |f|
      - if @app.errors.any?
        #error_explanation
          h2 = "#{pluralize(@app.errors.count, "error")} prohibited this app from being saved:"
          ul
            - @app.errors.full_messages.each do |message|
              li = message

      .field.form-group
        = f.label :name, class: 'col-lg-2 control-label'
        = f.text_field :name, class: 'col-lg-10'
      .field.form-group
        = f.label :description, class: 'col-lg-2 control-label'
        = f.text_area :description, class: 'col-lg-10', rows: '3'
      .field.form-group
        = f.label :host_group, class: 'col-lg-2 control-label'
        = f.text_area :host_group, class: 'col-lg-10'
      .field.form-group
        = f.label :metadata, class: 'col-lg-2 control-label'
        = f.text_field :metadata, class: 'col-lg-10'
      .actions = f.submit 'Save'

app/views/v1/apps/edit.html.slim
h1 Editing app

== render 'form'

= link_to 'Show', @app
'|
= link_to 'Back', apps_path

app/views/v1/apps/index.html.slim
h1 Listing apps

= link_to 'New App', new_app_path, class: "btn btn-primary btn-lg"

table#app_index.table.table-striped.table-hover
  thead
    tr
      th Name
      th Description
      th Host group
      th Metadata
      th
      th
      th

  tbody
    - @apps.each do |app|
      tr
        td = app.name
        td = app.description
        td = app.host_group
        td = app.metadata
        td = link_to 'Show', app, class: "btn btn-primary"
        td = link_to 'Edit', edit_app_path(app), class: "btn btn-info"
        td = link_to 'Destroy', app, data: {:confirm => 'Are you sure?'}, :method => :delete, class: "btn btn-danger"

br

app/views/v1/apps/new.html.slim
h1 New app

== render 'form'

= link_to 'Back', apps_path

app/views/v1/apps/show.html.slim
p#notice = notice

p
  strong Name:
  = @app.name
p
  strong Description:
  = @app.description
p
  strong Host group:
  = @app.host_group
p
  strong Metadata:
  = @app.metadata

= link_to 'Edit', edit_app_path(@app)
'|
= link_to 'Back', apps_path